/** Independent Java study examples. Methods belong inside a class. */
export const javaExamples: Record<string, string> = {
  complexity: `static long total(int[] a) {\n    long sum = 0;\n    for (int x : a) sum += x;\n    return sum;\n}`,
  arrays: `static int largest(int[] a) {\n    if (a.length == 0) throw new IllegalArgumentException("Empty array");\n    int best = a[0];\n    for (int x : a) best = Math.max(best, x);\n    return best;\n}`,
  hashing: `static int[] twoSum(int[] a, int target) {\n    Map<Integer, Integer> seen = new HashMap<>();\n    for (int i = 0; i < a.length; i++) {\n        if (seen.containsKey(target - a[i]))\n            return new int[]{seen.get(target - a[i]), i};\n        seen.put(a[i], i);\n    }\n    return new int[0];\n}`,
  pointers: `static boolean hasPair(int[] a, int target) {\n    int l = 0, r = a.length - 1;\n    while (l < r) {\n        long sum = (long) a[l] + a[r];\n        if (sum == target) return true;\n        if (sum < target) l++; else r--;\n    }\n    return false;\n}`,
  window: `static long bestWindow(int[] a, int k) {\n    if (k < 1 || k > a.length) throw new IllegalArgumentException();\n    long sum = 0;\n    for (int i = 0; i < k; i++) sum += a[i];\n    long best = sum;\n    for (int i = k; i < a.length; i++) {\n        sum += (long) a[i] - a[i-k];\n        best = Math.max(best, sum);\n    }\n    return best;\n}`,
  search: `static int binarySearch(int[] a, int target) {\n    int l = 0, r = a.length - 1;\n    while (l <= r) {\n        int m = l + (r - l) / 2;\n        if (a[m] == target) return m;\n        if (a[m] < target) l = m + 1; else r = m - 1;\n    }\n    return -1;\n}`,
  linked: `static class Node {\n    int value; Node next;\n    Node(int value) { this.value = value; }\n}\nstatic Node reverse(Node head) {\n    Node previous = null;\n    while (head != null) {\n        Node next = head.next;\n        head.next = previous;\n        previous = head;\n        head = next;\n    }\n    return previous;\n}`,
  stacks: `static boolean valid(String s) {\n    Deque<Character> stack = new ArrayDeque<>();\n    for (char c : s.toCharArray()) {\n        if (c == '(' || c == '[' || c == '{') stack.push(c);\n        else {\n            if (stack.isEmpty()) return false;\n            char open = stack.pop();\n            if (c == ')' && open != '(' || c == ']' && open != '['\n                || c == '}' && open != '{') return false;\n        }\n    }\n    return stack.isEmpty();\n}\n// Input contains only ()[]{} characters.`,
  recursion: `static long factorial(int n) {\n    if (n < 0 || n > 20) throw new IllegalArgumentException();\n    if (n <= 1) return 1;\n    return n * factorial(n - 1);\n}`,
  sorting: `static int[][] merge(int[][] intervals) {\n    Arrays.sort(intervals, Comparator.comparingInt(a -> a[0]));\n    List<int[]> result = new ArrayList<>();\n    for (int[] next : intervals) {\n        if (result.isEmpty() || result.get(result.size()-1)[1] < next[0])\n            result.add(next.clone());\n        else {\n            int[] last = result.get(result.size()-1);\n            last[1] = Math.max(last[1], next[1]);\n        }\n    }\n    return result.toArray(new int[0][]);\n}`,
  trees: `static class Tree { int value; Tree left, right; }\nstatic int depth(Tree root) {\n    if (root == null) return 0;\n    return 1 + Math.max(depth(root.left), depth(root.right));\n}`,
  heaps: `static int kthLargest(int[] a, int k) {\n    if (k < 1 || k > a.length) throw new IllegalArgumentException();\n    PriorityQueue<Integer> heap = new PriorityQueue<>();\n    for (int x : a) {\n        heap.offer(x);\n        if (heap.size() > k) heap.poll();\n    }\n    return heap.peek();\n}`,
  graphs: `static int[] distances(List<List<Integer>> graph, int start) {\n    int[] dist = new int[graph.size()];\n    Arrays.fill(dist, -1);\n    Queue<Integer> queue = new ArrayDeque<>();\n    dist[start] = 0; queue.offer(start);\n    while (!queue.isEmpty()) {\n        int u = queue.poll();\n        for (int v : graph.get(u)) {\n            if (dist[v] == -1) {\n                dist[v] = dist[u] + 1; queue.offer(v);\n            }\n        }\n    }\n    return dist;\n}`,
  greedy: `static int maxEvents(int[][] intervals) {\n    Arrays.sort(intervals, Comparator.comparingInt(a -> a[1]));\n    long end = Long.MIN_VALUE;\n    int count = 0;\n    for (int[] event : intervals) {\n        if (event[0] >= end) { end = event[1]; count++; }\n    }\n    return count;\n}`,
  dp: `static long stairs(int n) {\n    if (n < 0 || n > 91) throw new IllegalArgumentException();\n    long a = 1, b = 1;\n    for (int i = 2; i <= n; i++) {\n        long next = a + b; a = b; b = next;\n    }\n    return b;\n}`,
  advanced: `static int singleNumber(int[] a) {\n    int value = 0;\n    for (int x : a) value ^= x;\n    return value;\n}\n// Every value except one must appear exactly twice.`,
};
